FROM denoland/deno:ubuntu

WORKDIR /fermater

# Capa 3: Creamos un usuario no privilegiado 'user_sin_permisos'
RUN adduser -D -s /bin/sh user_sin_permisos

# Capa 4: Pasamos los archivos del proyecto y los hacemos pertenecientes al user_sin_permisos
COPY --chown=user_sin_permisos:user_sin_permisos ./test ./test
COPY --chown=user_sin_permisos:user_sin_permisos ./lib ./lib
COPY --chown=user_sin_permisos:user_sin_permisos ./deno.json ./
COPY --chown=user_sin_permisos:user_sin_permisos ./deno.lock ./

# Capa 5: La ejecucion la hacemos con el user sin permisos ya que es el unico que podemos garantizar
USER user_sin_permisos
CMD ["deno", "test"]