# docker run -u 1001 -t -v `pwd`:/app/test jorgelopez17/fermater:latest

FROM almalinux:minimal

WORKDIR /fermater

RUN microdnf install curl unzip shadow-utils -y

RUN curl -fsSL https://deno.land/install.sh | DENO_INSTALL=/usr/local sh

RUN mkdir -p /fermater/.deno_cache
RUN chmod 777 /fermater/.deno_cache
ENV DENO_DIR=/fermater/.deno_cache
COPY deno.json deno.lock ./

RUN deno cache deno.json
RUN rm deno.lock deno.json

CMD ["tail", "-f", "/dev/null"]
