FROM denoland/deno:ubuntu

WORKDIR /fermater

RUN useradd -ms /bin/bash user_sin_permisos

RUN mkdir -p /fermater/.deno_cache
RUN chown -R user_sin_permisos:user_sin_permisos /fermater/.deno_cache
ENV DENO_DIR=/fermater/.deno_cache

COPY --chown=user_sin_permisos:user_sin_permisos ./test ./test
COPY --chown=user_sin_permisos:user_sin_permisos ./lib ./lib
COPY --chown=user_sin_permisos:user_sin_permisos ./deno.json ./
COPY --chown=user_sin_permisos:user_sin_permisos ./deno.lock ./

USER user_sin_permisos

RUN deno cache test/test.js

CMD ["deno", "test"]